# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: name_server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11name_server.proto\x12\x0bname_server\"H\n\x10\x41\x64\x64\x43lientRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\x12\x1f\n\x17\x63lient_address_and_port\x18\x02 \x01(\t\"(\n\x11\x43lientNameRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\"B\n\nClientInfo\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\x12\x1f\n\x17\x63lient_address_and_port\x18\x02 \x01(\t\"&\n\x12InfoFromNameServer\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x05\"\"\n\tErrorInfo\x12\x15\n\rerror_message\x18\x01 \x01(\x05\"\x83\x01\n\x15GetClientInfoResponse\x12\x31\n\x0e\x63onnectionInfo\x18\x01 \x01(\x0b\x32\x17.name_server.ClientInfoH\x00\x12+\n\terrorInfo\x18\x02 \x01(\x0b\x32\x16.name_server.ErrorInfoH\x00\x42\n\n\x08response2\xb4\x01\n\nNameServer\x12S\n\rGetClientInfo\x12\x1e.name_server.ClientNameRequest\x1a\".name_server.GetClientInfoResponse\x12Q\n\x0f\x41\x64\x64ToNameServer\x12\x1d.name_server.AddClientRequest\x1a\x1f.name_server.InfoFromNameServerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'name_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDCLIENTREQUEST']._serialized_start=34
  _globals['_ADDCLIENTREQUEST']._serialized_end=106
  _globals['_CLIENTNAMEREQUEST']._serialized_start=108
  _globals['_CLIENTNAMEREQUEST']._serialized_end=148
  _globals['_CLIENTINFO']._serialized_start=150
  _globals['_CLIENTINFO']._serialized_end=216
  _globals['_INFOFROMNAMESERVER']._serialized_start=218
  _globals['_INFOFROMNAMESERVER']._serialized_end=256
  _globals['_ERRORINFO']._serialized_start=258
  _globals['_ERRORINFO']._serialized_end=292
  _globals['_GETCLIENTINFORESPONSE']._serialized_start=295
  _globals['_GETCLIENTINFORESPONSE']._serialized_end=426
  _globals['_NAMESERVER']._serialized_start=429
  _globals['_NAMESERVER']._serialized_end=609
# @@protoc_insertion_point(module_scope)
