# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import name_server_pb2 as name__server__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in name_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NameServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClientInfo = channel.unary_unary(
                '/name_server.NameServer/GetClientInfo',
                request_serializer=name__server__pb2.ClientNameRequest.SerializeToString,
                response_deserializer=name__server__pb2.GetClientInfoResponse.FromString,
                _registered_method=True)
        self.AddToNameServer = channel.unary_unary(
                '/name_server.NameServer/AddToNameServer',
                request_serializer=name__server__pb2.AddClientRequest.SerializeToString,
                response_deserializer=name__server__pb2.InfoFromNameServer.FromString,
                _registered_method=True)


class NameServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToNameServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientInfo,
                    request_deserializer=name__server__pb2.ClientNameRequest.FromString,
                    response_serializer=name__server__pb2.GetClientInfoResponse.SerializeToString,
            ),
            'AddToNameServer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToNameServer,
                    request_deserializer=name__server__pb2.AddClientRequest.FromString,
                    response_serializer=name__server__pb2.InfoFromNameServer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'name_server.NameServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NameServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/name_server.NameServer/GetClientInfo',
            name__server__pb2.ClientNameRequest.SerializeToString,
            name__server__pb2.GetClientInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToNameServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/name_server.NameServer/AddToNameServer',
            name__server__pb2.AddClientRequest.SerializeToString,
            name__server__pb2.InfoFromNameServer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
